[package]
name = "holochain_locksmith"
version = "0.0.42-alpha5"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "helpers for mutex deadlock diagnosis"
keywords = ["holochain", "holo", "p2p"]
license = "GPL-3.0-only"
readme = "README.md"
documentation = "https://github.com/holochain/holochain-rust"
repository = "https://github.com/holochain/holochain-rust"

[dependencies]
backtrace = "=0.3.27"
chrono = "=0.4.6"
crossbeam-channel = "=0.3.8"
lazy_static = "=1.4.0"
log = "=0.4.8"
parking_lot ="=0.9.0"
snowflake = "=1.3.0"
holochain_persistence_api = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_lmdb = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_file = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_pickle = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_mem = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
lib3h_protocol = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
lib3h = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
