[package]
name = "holochain_metrics"
version = "0.0.42-alpha5"
description = "Holochain analytics from logs and other metrics"
license = "GPL-3.0-only"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
shrinkwraprs = "=0.2.1"
serde = { version = "=1.0.89", features = ["rc"] }
serde_derive = "=1.0.89"
holochain_locksmith = { version = "=0.0.42-alpha5", path = "../locksmith" }
lazy_static = "=1.4.0"
num-traits = "=0.2.6"
num-derive = "=0.2.4"
toml = "=0.5.0"
log = "=0.4.8"
holochain_logging = "=0.0.4"
regex = "=1.1.2"
env_logger = "=0.6.1"
rand = "0.7.2"
## For cloudwatch logs / sts
rusoto_sts = "=0.40.0"
rusoto_logs = "=0.40.0"
rusoto_core = "=0.40.0"
rusoto_credential = "=0.40.0"
## For descriptive statistics on metrics
streaming-stats = "=0.2.2"
csv = "=1.1"
structopt = "=0.3.3"
structopt-derive = "=0.3.3"
strip-ansi-escapes = "=0.1.0"
snowflake = "=1.3.0"
crossbeam-channel = "=0.3.8"
chrono = "0.4.6"
holochain_persistence_api = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_lmdb = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_file = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_pickle = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_mem = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
lib3h_protocol = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
lib3h = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
lib3h_sodium = { git = "https://github.com/holochain/lib3h", branch = "transactional" }

[dev-dependencies]
tempfile = "=3.0.7"
