[workspace]

members = [
  "benchmarks",
  "cli",
  "common",
  "conductor",
  "conductor_api",
  "conductor_wasm",
  "core_api_c_binding",
  "core",
  "dna_c_binding",
  "dpki",
  "hdk-proc-macros",
  "hdk-rust",
  "logging",
  "net",
  "test_bin",
  "walkman",
]
exclude = [
  "test_utils",
  "app_spec",
  "app_spec_proc_macro",
  "nodejs_conductor/native",
]
