[workspace]

members = [
  "benchmarks",
  "cli",
  "common",
  "conductor",
  "conductor_api",
  "conductor_wasm",
  "core",
  "core_api_c_binding",
  "core_types",
  "dna_c_binding",
  "dpki",
  "hdk-proc-macros",
  "hdk-rust",
  "logging",
  "net",
  "wasm_utils"
]
exclude = [
  "test_utils",
  "app_spec",
  "app_spec_proc_macro",
  "nodejs_conductor/native",
]

[patch."https://github.com/holochain/holochain-rust"]
holochain_core_types = { path = "./core_types" }

[patch."https://github.com/holochain/holochain-tracing"]
holochain_tracing = "=0.0.1"
