[package]
name = "remove-dev-dependencies"
description = "adapted from futures-rs to workaround a cargo bug"
version = "0.0.42-alpha5"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
toml_edit = "0.1.3"
holochain_persistence_api = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_lmdb = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_file = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_pickle = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_mem = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
lib3h_protocol = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
lib3h = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
lib3h_sodium = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
