[package]
name = "hdk"
edition = "2018"
version = "0.0.42-alpha5"
description = "holochain hdk"
license = "GPL-3.0-only"
repository = "https://github.com/holochain/holochain-rust"
documentation = "https://docs.rs/hdk"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
bitflags = "=1.2.1"
lazy_static = "=1.4.0"
holochain_wasm_utils = { version = "=0.0.42-alpha5", path = "../wasm_utils" }
holochain_core_types = { version = "=0.0.42-alpha5", path = "../core_types" }
holochain_json_api = "=0.0.17"
holochain_json_derive = "=0.0.17"
holochain_persistence_api = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
pretty_assertions = "=0.6.1"
env_logger = "=0.6.1"
url = "=2.1.0"
holochain_persistence_lmdb = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_file = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_pickle = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
holochain_persistence_mem = { git = "https://github.com/holochain/holochain-persistence", branch = "transactional" }
lib3h_protocol = { git = "https://github.com/holochain/lib3h", branch = "transactional" }
lib3h = { git = "https://github.com/holochain/lib3h", branch = "transactional" }

[dev-dependencies]
test_utils = { version = "=0.0.42-alpha5", path = "../../test_utils" }
holochain_conductor_lib = { version = "=0.0.42-alpha5", path = "../conductor_lib" }
holochain_core = { version = "=0.0.42-alpha5", path = "../core" }
holochain_core_types = { version = "=0.0.42-alpha5", path = "../core_types" }
tempfile = "=3.0.7"
boolinator = "=2.4.0"
