[package]
name = "sim2h_server"
version = "0.0.41-alpha4"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "A simulation of lib3h - server executable"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
categories = ["network-programming"]
license = "GPL-3.0-only"
readme = "README.md"
documentation = "https://github.com/holochain/sim2h"
repository = "https://github.com/holochain/sim2h"

[dependencies]
sim2h = { version = "=0.0.41-alpha4", path = "../sim2h" }
detach = "=0.0.19"
lib3h = { path = "/home/michael/Holo/lib3h/crates/lib3h", version = "=0.0.25" }
lib3h_protocol = { path = "/home/michael/Holo/lib3h/crates/lib3h_protocol" }
lib3h_sodium = { path = "/home/michael/Holo/lib3h/crates/sodium" }
log = "0.4.8"
env_logger = "0.7.0"
structopt = "=0.2.15"
